export {
	useUpdateAvatarMutation,
	useUpdateMutation,
	useUpdateSignatureMutation,
	usePasswordGenerateCodeMutation,
	useSetNewPasswordMutation,
	useTagsQuery,
	useLazyAlbumsQuery,
	useAlbumCreateMutation,
	useUploadImagesMutation,
	useChangeVisibilityImageMutation,
	useDeleteImageMutation,
	useAlbumUpdateMutation,
	useAlbumDeleteMutation,
	useDeleteAvatarMutation,
} from "./settings-api";
