export { profileCardValidator } from "./profile-card.validator"
export { mainCardValidator } from "./main-card.validator"
export { passwordValidator } from "./password-card.validator"
export { signatureValidator } from "./signature-card.validator"
export { createAlbumValidator } from "./create-album.validator"